### ISSUE TITLE
demo.py

### ISSUE THREAD

**Issue by weidu3** [EternalGoldenBraid/PoseEstimation_pipeline#1]
Hi, thank you for opening such a great work, I have some problems when I run demo.py, how can I solve it?

(pose) gln@gln:~/PoseEstimation/PoseEstimation_pipeline$ python demo.py 
{'1': {'diameter': 0.2136586, 'name': 'box'}, '2': {'diameter': 0.2136586, 'name': 'obj2'}, '3': {'diameter': 0.2475, 'name': 'head_phones'}}
Depth Scale is:  0.0010000000474974513
Camera intrinsics: tensor([[607.4683,   0.0000, 313.1549],
        [  0.0000, 607.5413, 254.3604],
        [  0.0000,   0.0000,   1.0000]])
libEGL warning: DRI2: failed to create dri screen
libEGL warning: Not allowed to force software rendering when API explicitly selects a hardware device.
libEGL warning: DRI2: failed to create dri screen
Traceback (most recent call last):
  File "/home/gln/PoseEstimation/PoseEstimation_pipeline/demo.py", line 189, in <module>
    main(args)
  File "/home/gln/PoseEstimation/PoseEstimation_pipeline/demo.py", line 54, in main
    dataset = demo_dataset.Dataset(data_dir=dataroot/ cfg.DATASET_NAME, cfg=cfg,
  File "/home/gln/PoseEstimation/PoseEstimation_pipeline/dataset/demo_dataset.py", line 50, in __init__
    self.obj_renderer = rendering.Renderer(width=self.cfg.RENDER_WIDTH, height=self.cfg.RENDER_HEIGHT)
  File "/home/gln/PoseEstimation/PoseEstimation_pipeline/lib/rendering.py", line 236, in __init__
    self._renderer = pyrender.OffscreenRenderer(width, height)
  File "/home/gln/anaconda3/envs/pose/lib/python3.9/site-packages/pyrender/offscreen.py", line 31, in __init__
    self._create()
  File "/home/gln/anaconda3/envs/pose/lib/python3.9/site-packages/pyrender/offscreen.py", line 149, in _create
    self._platform.init_context()
  File "/home/gln/anaconda3/envs/pose/lib/python3.9/site-packages/pyrender/platforms/egl.py", line 177, in init_context
    assert eglInitialize(self._egl_display, major, minor)
  File "/home/gln/anaconda3/envs/pose/lib/python3.9/site-packages/OpenGL/platform/baseplatform.py", line 402, in __call__
    return self( *args, **named )
  File "/home/gln/anaconda3/envs/pose/lib/python3.9/site-packages/OpenGL/error.py", line 228, in glCheckError
    raise GLError(
OpenGL.error.GLError: GLError(
	err = 12289,
	baseOperation = eglInitialize,
	cArguments = (
		<OpenGL._opaque.EGLDisplay_pointer object at 0x7fefcf1dfcc0>,
		c_long(0),
		c_long(0),
	),
	result = 0
)
Exception ignored in: <function Renderer.__del__ at 0x7ff0d010ca60>
Traceback (most recent call last):
  File "/home/gln/PoseEstimation/PoseEstimation_pipeline/lib/rendering.py", line 248, in __del__
    self._renderer.delete()
AttributeError: 'Renderer' object has no attribute '_renderer'

**Comment by EternalGoldenBraid** [comment]
Pardon the delay. Did you resolve this? It sounds to me like a in issue with your library versions. Have you checked that your pyrender version matches the requirements?
